"""Answer-quality gate: is a 200's text a real answer, or an answer with junk
glued on (or only junk)?

MEASURED LIVE (llm7/GLM-5.3-Flash): the model answered correctly, then kept
generating until max_tokens, and the hub served the whole thing as a success:

    "OK出具证明的，原试题解析 做题如有雷同，纯属巧合…"           (prompt had no CJK)
    "6510</arg_value></tool_call>6510</arg_value></tool_call>The user asked"

Every existing check (empty 200, relay error page, refusal, typed tool call)
looked for a BAD answer; none looked for a GOOD answer followed by garbage, so
both counted as clean deliveries and kept that model winning hop 1.

A second live batch (same model, "What is N plus 1? Answer with only the
number.", max_tokens 40) slipped past those first detectors:

    "2826HAMSTER-2826282628262826282628262826"   -> _glued_loop
    "1573 1573 ------------------------------"   -> _separator_run
    "5499 картинка внутри Thinking content: 5"   -> _script_switch (short head)
                                                    + _reasoning_leak
    '8446"Sfc cover" is an additional paramet'   -> _constrained_extra

Leaf module on purpose (no app imports): pure text in, verdict out, trivially
testable and cheap enough to run on every non-streamed answer and once at the
end of every stream.

CONSERVATIVE by design. A false positive either trims a real answer (salvage)
or costs a hop, so every detector demands a strong, specific signal:
  * code (fenced blocks, inline `spans`) is masked out before the script and
    markup checks; the loop checks see inline code verbatim and each fenced
    block as a distinct run-breaker (see _mask_fences_distinct);
  * a repetition loop must run to the END of the answer (or repeat
    _MID_MIN_RUN times mid-text): repeated lines inside raw HTML/CSS/CSV or
    a chorus are content, not a runaway;
  * the script-switch check only fires when the PROMPT never used that script
    and never names its language / asks for a translation, AND the switch is
    either glued straight onto the answer ("OK出具…") or the reply ran to the
    token cap -- a list of greetings after "Here are some:" is neither;
  * markup leaks are only judged when no tools were offered (with tools, the
    typed-tool-call / tool_rescue path owns that shape) and the prompt itself
    does not mention the tag; reasoning markers only at an odd place (a reply
    that OPENS with a <think> block is left alone);
  * the brevity trim needs an IMPERATIVE constraint in the LAST user turn and
    a leading answer that ends cleanly (see _constrained_extra's guards);
  * truncation alone (finish_reason "length") is reported but never fails an
    answer: a plain truncation is common and legitimate (see
    app._chat_json_starved's notes).

A third live sample (2026-09-27, Claude Code over /v1/messages, streamed,
model "max", "What is N plus 1? Reply with only the number.") slipped past
all of the above:

    "4349âmara=METADATA:8;Note: TOKEN count=298121; REF:5"
                                                  -> _glued_foreign
                                                     + _meta_leak

Claude Code offers tools (so the brevity trim stood down) and wraps its
question in <system-reminder> blocks (so the "last user turn" was a long
pasted-looking text); "â" is Latin-1, so no script switch either. Brevity is
now read from the user's own words (_instruction), and the two new detectors
work on tool turns too because they need a junk SHAPE, not just "more text".
"""
import functools
import re
import unicodedata

__all__ = ["inspect", "inspect_tail", "brevity_ask"]


# Blocks a CLI injects into a USER turn that are not the user speaking:
# Claude Code's <system-reminder>, Codex's <environment_context> and its
# AGENTS.md <INSTRUCTIONS> / <user_instructions>, slash-command echoes.
# Mirrors ctxwin._WRAPPER_BLOCK_RE / _WRAPPER_LINE_RE -- keep the two in sync
# (copied, not imported: this module stays a leaf).
_WRAPPER_BLOCK_RE = re.compile(
    r"<(system-reminder|environment_context|user_instructions|INSTRUCTIONS|"
    r"user-prompt-submit-hook|command-name|command-message|command-args|"
    r"local-command-stdout|local-command-stderr|turn_aborted)>.*?</\1>",
    re.S | re.I)
_WRAPPER_LINE_RE = re.compile(
    r"^\s*#\s*AGENTS\.md instructions for .*$|"
    r"^\s*Caveat: The messages below were generated by the user while running "
    r"local commands.*$", re.M | re.I)


@functools.lru_cache(maxsize=64)
def _instruction(prompt):
    """`prompt` without CLI wrapper blocks: what the USER typed. MEASURED
    (claude 2.1.x): the last user turn is "<system-reminder>...CLAUDE.md,
    skills...</system-reminder>What is N plus 1? Reply with only the number."
    -- read whole, it is over _BRIEF_PROMPT_MAX and full of "then"/"why", so
    the brevity ask inside it was never seen."""
    if not isinstance(prompt, str) or not prompt:
        return prompt
    if "<" not in prompt and "#" not in prompt and "Caveat" not in prompt:
        return prompt
    out = _WRAPPER_BLOCK_RE.sub("\n", prompt)
    out = _WRAPPER_LINE_RE.sub("", out)
    return out.strip()

# Anything longer is judged on its head (script switch) and tail (loops and
# leaks live at the END of a runaway generation); keeps the check O(cap).
_MAX_SCAN = 24000
_RATIO_WINDOW = 1200            # script-share is judged on this much of the rest

_FENCE_RE = re.compile(r"```.*?(?:```|\Z)", re.S)
_INLINE_CODE_RE = re.compile(r"`[^`\n]{1,300}`")


def _blank(m):
    # per LINE, not per char: a 20 KB code block is ~700 lines, not 20k subs
    return "\n".join(" " * len(part) for part in m.group(0).split("\n"))


def _mask_code(text, partial=False):
    """Same-length copy of `text` with code blanked to spaces (newlines kept),
    so every index found on the mask is valid on the original.

    `partial`: the text is a stream still in progress, so an inline span whose
    closing backtick has not arrived yet ("wrapped in `<think") is code too --
    the fence rule's end-of-text fallback, for inline code."""
    if "`" not in text:
        return text
    out = _INLINE_CODE_RE.sub(_blank, _FENCE_RE.sub(_blank, text))
    if partial:
        i = out.find("`", out.rfind("\n") + 1)
        if i != -1 and len(out) - i <= 300:
            out = out[:i] + " " * (len(out) - i)
    return out


# Loop checks need a DIFFERENT mask: blanking made "- `app.py` updated" and
# "- `cli.py` updated" identical, and turned fenced blocks into skipped blank
# lines, so prose after each of three code blocks read as three copies. Inline
# code stays verbatim here; each fenced block becomes a same-length run of its
# OWN private-use char, which breaks a line run and never equals another block.
_PUA_BASE = 0xE000
_PUA_SPAN = 0x1800
_PUA_RE = re.compile("[-]")


def _mask_fences_distinct(text):
    if "`" not in text:
        return text
    counter = [0]

    def sub(m):
        ch = chr(_PUA_BASE + counter[0] % _PUA_SPAN)
        counter[0] += 1
        return "\n".join(ch * len(part) for part in m.group(0).split("\n"))
    return _FENCE_RE.sub(sub, text)


# --------------------------------------------------------------------------- #
# (a) runaway continuation: the reply switches to a script the prompt never used
# --------------------------------------------------------------------------- #
# key -> (char ranges, language names that mean "the prompt asked for it",
#         min run). Greek needs RUNS of 3+ letters: a lone alpha/beta/pi is
# ordinary maths notation, "καλημέρα σας" is a language.
_SCRIPTS = {
    "cjk": ("぀-ヿ㐀-䶿一-鿿가-힯豈-﫿"
            "　-〿＀-￯",
            ("chinese", "mandarin", "cantonese", "japanese", "korean", "kanji",
             "hanzi", "hiragana", "katakana", "hangul", "pinyin", "chinois",
             "japonais", "coreen", "coréen", "chino", "japon", "cjk"), 1),
    "cyrillic": ("Ѐ-ӿ",
                 ("russian", "ukrainian", "cyrillic", "bulgarian", "serbian",
                  "russe", "kazakh", "belarus", "mongolian", "macedonian"), 1),
    "arabic": ("؀-ۿݐ-ݿ",
               ("arabic", "arabe", "persian", "farsi", "urdu", "pashto",
                "quran", "coran"), 1),
    "hebrew": ("֐-׿", ("hebrew", "hébreu", "hebreu", "yiddish"), 1),
    "greek": ("Ͱ-Ͽἀ-῿", ("greek", "grec", "griego", "hellenic"), 3),
    "thai": ("฀-๿", ("thai", "thaï"), 1),
    "devanagari": ("ऀ-ॿ", ("hindi", "sanskrit", "marathi", "nepali",
                                     "devanagari"), 1),
    "armenian": ("԰-֏", ("armenian", "arménien"), 1),
    "georgian": ("Ⴀ-ჿ", ("georgian", "géorgien"), 1),
    "bengali": ("ঀ-৿", ("bengali", "bangla", "assamese"), 1),
    "gurmukhi": ("਀-੿", ("punjabi", "gurmukhi"), 1),
    "gujarati": ("઀-૿", ("gujarati",), 1),
    "tamil": ("஀-௿", ("tamil",), 1),
    "telugu": ("ఀ-౿", ("telugu",), 1),
    "kannada": ("ಀ-೿", ("kannada",), 1),
    "malayalam": ("ഀ-ൿ", ("malayalam",), 1),
    "sinhala": ("඀-෿", ("sinhala", "sinhalese"), 1),
    "lao": ("຀-໿", ("lao", "laotian"), 1),
    "khmer": ("ក-៿", ("khmer", "cambodian"), 1),
    "myanmar": ("က-႟", ("burmese", "myanmar"), 1),
    "ethiopic": ("ሀ-፿", ("amharic", "tigrinya", "ethiopic"), 1),
}
# presence ("did the prompt use this script at all") and detection (min run)
_SCRIPT_ANY = {k: re.compile("[" + rng + "]") for k, (rng, _n, _r) in _SCRIPTS.items()}
_SCRIPT_RES = {k: re.compile("[" + rng + "]" + ("{%d,}" % run if run > 1 else ""))
               for k, (rng, _n, run) in _SCRIPTS.items()}
_ANY_FOREIGN_RE = re.compile("[" + "".join(r for r, _n, _r in _SCRIPTS.values()) + "]")
# A prompt using any of these asked for other-language output on purpose.
_TRANSLATE_HINTS = ("translat", "tradu", "übersetz", "multilingual",
                    "multilingue", "unicode", "transliterat")
_LATIN_LETTER_RE = re.compile(r"[A-Za-zÀ-ɏ]")
_MIN_FOREIGN_CHARS = 8          # a word or two of foreign script is never junk
_FOREIGN_SHARE = 0.6            # ...and the rest of the reply must be MOSTLY it
# "5499 картинка внутри Thinking content: 5": the switch follows a BARE short
# answer (one number or one ASCII token, nothing else) -- a complete reply
# that kept going. That shape is signal on its own, on any finish reason, so
# the share bar drops (that junk switched back to Latin mid-way). A head with
# a space in it ("It's called Метрополитен") is a sentence introducing a
# foreign word and never takes this branch.
_SHORT_HEAD_RE = re.compile(r"[-+]?\d[\d,.]*%?|[A-Za-z0-9]{1,16}")
_SHORT_SHARE = 0.3


def _script_switch(text, masked, prompt_text, finish_reason, at_start=True):
    if prompt_text is None:
        return None             # nothing to compare against -> never guess
    if not _ANY_FOREIGN_RE.search(masked):
        return None             # the common all-Latin reply: one scan, done
    low = prompt_text.lower()
    if any(h in low for h in _TRANSLATE_HINTS):
        return None
    best = None
    for key, rx in _SCRIPT_RES.items():
        if _SCRIPT_ANY[key].search(prompt_text) or any(n in low for n in _SCRIPTS[key][1]):
            continue            # the prompt itself used / asked for this script
        m = rx.search(masked)
        if not m:
            continue
        pos = m.start()
        prefix = text[:pos]
        if not re.search(r"\w", prefix):
            continue            # the reply STARTED in that script: not a switch
        rest = masked[pos:pos + _RATIO_WINDOW]
        n_foreign = sum(len(x) for x in rx.findall(rest))
        if n_foreign < _MIN_FOREIGN_CHARS:
            continue
        n_latin = len(_LATIN_LETTER_RE.findall(rest))
        share = n_foreign / float(n_foreign + n_latin)
        glued = prefix[-1].isascii() and prefix[-1].isalnum()
        mostly = share >= _FOREIGN_SHARE and (glued or finish_reason == "length")
        # at_start: a clipped long answer's head is not the reply's head
        short = (at_start and share >= _SHORT_SHARE
                 and _SHORT_HEAD_RE.fullmatch(prefix.strip()) is not None)
        if not (mostly or short):
            continue
        if best is None or pos < best:
            best = pos
    return best


# --------------------------------------------------------------------------- #
# (b) repetition loops
# --------------------------------------------------------------------------- #
_LINE_MIN_LEN = 12
# A loop only counts when it runs to the END of the answer (a runaway loops
# until the cap): 3 copies there if the reply hit the token cap, 5 otherwise
# (a song may legitimately end on a line sung three times). Mid-text repeats
# -- four identical `<span class="star">` lines in an HTML page, a chorus --
# are content, and need _MID_MIN_RUN copies before they count.
_LINE_MIN_RUN = 3
_END_MIN_RUN = 5
_MID_MIN_RUN = 8
# finish_reason for text of a stream still in progress: its current end is not
# the answer's end (every mid-text repeat is briefly "at the end"), so a loop
# reaching it needs the MID-text copy count.
PARTIAL = "__partial__"
# A looping unit is 8..160 chars: shorter is "ha ha ha" / "0x00, 0x00" land,
# longer is a paragraph (caught per line by _line_loop).
_UNIT_MIN = 8
_UNIT_MAX = 160
_PRECHECK_IGNORE = frozenset(" \t\r\n|")


def _unit_is_meaningful(unit):
    stripped = unit.strip()
    if not stripped or stripped.startswith("|"):
        return False            # markdown table rows legitimately repeat
    distinct = {c for c in stripped if not c.isspace()}
    letters = sum(1 for c in stripped if c.isalpha())
    return len(distinct) >= 5 and letters >= 3


def _line_is_meaningful(norm):
    # short lines ("---", "}", "Yes.") and table rows repeat legitimately
    return (len(norm) >= _LINE_MIN_LEN and not norm.startswith("|")
            and any(c.isalnum() for c in norm))


def _end_min_run(finish_reason):
    if finish_reason == PARTIAL:
        return _MID_MIN_RUN
    return _LINE_MIN_RUN if finish_reason == "length" else _END_MIN_RUN


# STRUCTURED LINES repeat legitimately: list items ("- TBD by the owner",
# "- [ ] Review the migration"), table rows without a leading pipe, test
# runner / log output ("test_x ... ok", "[WARN] retrying connection",
# "PASSED", "12:00:01 GET /health 200"), indented code/output, key: value
# records, REPL/shell lines. A runaway loop never stops by itself -- it runs to
# the token cap -- so for these lines:
#   * finish "length": the plain rule (3 copies at the end: the cap IS the loop);
#   * a natural finish: a run is content up to _STRUCT_END_MAX_RUN copies (the
#     model chose to stop there);
#   * a stream still going: _STRUCT_PARTIAL_MIN_RUN copies must reach the end;
#   * mid-text (more content follows): _STRUCT_PARTIAL_MIN_RUN copies, not 8.
_STRUCT_PARTIAL_MIN_RUN = 16
_STRUCT_END_MAX_RUN = 50
_STRUCT_LINE_RE = re.compile(
    r"""^(?:
        (?:\ {4}|\t)                                   # indented code / output
      | \s*(?:[-*+•]|\d{1,4}[.)]|[A-Za-z][.)])\s  # bullet / numbered item
      | \s*\[[^\]\n]{1,40}\]                           # [INFO] / [PASS] / [ ]
      | \s*\d{4}-\d{2}-\d{2}                           # dated log line
      | \s*\d{1,2}:\d{2}(?::\d{2})?\b                  # timed log line
      | \s*(?:PASS(?:ED)?|FAIL(?:ED)?|ok|not\ ok|OK|ERROR|WARN(?:ING)?|INFO
              |DEBUG|TRACE|SKIP(?:PED)?|XFAIL|XPASS)(?=[\s:\]]|$)  # test / log
      | \s*[✓✔✗✘×√]      # check / cross marks
      | \s*(?:>>>|\.\.\.|\$|PS\ [A-Z]:\\[^>]*>)\s      # REPL / shell prompt
      | \s*[A-Za-z_][\w.-]{0,30}(?:\ [A-Z][\w.-]*)?:\s+\S  # key: value record
    )""", re.X)
_STRUCT_END_RE = re.compile(r"(?:\.\.\.\s*(?:ok|OK|PASSED|FAILED|passed|failed|done)"
                            r"|\s(?:PASSED|FAILED|SKIPPED|ok|OK))\s*$")


def _line_is_structured(line):
    """A list item, table row, test/log output line, indented code or a
    key: value record -- shapes that repeat verbatim in real answers."""
    if not line or not line.strip():
        return False
    if line.count("|") >= 2 or "\t" in line.strip():
        return True             # a table row, with or without a leading pipe
    if "::" in line and re.search(r"\w::\w", line):
        return True             # pytest node ids / C++ scopes
    return bool(_STRUCT_LINE_RE.match(line) or _STRUCT_END_RE.search(line))


def _struct_end_allows(run, finish_reason):
    """True when a run of `run` structured lines reaching the text's end is
    content under `finish_reason` (see _STRUCT_LINE_RE's comment)."""
    if finish_reason == "length":
        return run < _LINE_MIN_RUN
    if finish_reason == PARTIAL:
        return run < _STRUCT_PARTIAL_MIN_RUN
    return run < _STRUCT_END_MAX_RUN


def _line_loop(masked, prompt_text, finish_reason=None):
    """Offset just past the first copy of a line repeated in a row: at least
    _MID_MIN_RUN copies anywhere, or _end_min_run copies running to the end.
    Structured lines (_line_is_structured) follow their own rule."""
    prev = None
    prev_raw = ""
    run = 0
    first_end = 0
    pos = 0

    def hit(norm):
        if not _line_is_meaningful(norm):
            return None
        if prompt_text and (norm + "\n" + norm) in prompt_text:
            return None
        return first_end

    for line in masked.split("\n"):
        start = pos
        pos += len(line) + 1
        norm = line.strip()
        if not norm:
            continue            # blank lines between copies do not break a run
        if _PUA_RE.search(norm):
            prev, run = None, 0     # a fenced code block breaks any run
            continue
        if norm == prev:
            run += 1
            if run >= (_STRUCT_PARTIAL_MIN_RUN if _line_is_structured(prev_raw)
                       else _MID_MIN_RUN):
                cut = hit(norm)
                if cut is not None:
                    return cut
        elif prev is not None and prev.startswith(norm) and not masked[pos:].strip():
            pass                # partial last copy of a loop cut by the cap
        else:
            prev = norm
            prev_raw = line
            run = 1
            first_end = start + len(line)
    if prev is not None and run >= _end_min_run(finish_reason):
        if _line_is_structured(prev_raw) and _struct_end_allows(run, finish_reason):
            return None
        return hit(prev)
    return None


def _loop_lines_structured(region):
    """True when every whole line of a loop region (its first line may be a
    partial copy, so it is skipped; so is a last line still being written)
    is a structured line."""
    lines = [ln for ln in region.split("\n")[1:] if ln.strip()]
    if len(lines) > 1 and any(o != lines[-1] and o.startswith(lines[-1])
                              for o in lines[:-1]):
        lines.pop()
    return bool(lines) and all(_line_is_structured(ln) for ln in lines)


def _tail_loop(masked, prompt_text, finish_reason=None):
    """Offset just past the FIRST copy of a unit that repeats, back to back and
    at least 3 times, up to the very END of the answer.

    End-anchored on purpose: a degenerate generation loops until the token cap,
    so the loop IS the tail. That turns the search into ~150 C-speed slice
    compares (one per candidate period) instead of a backtracking regex over
    the whole text -- MEASURED: `(.{8,160}?)\\1{2,}` cost ~40 ms on 4 KB of
    plain prose, twenty times the budget. Mid-text line loops are
    _line_loop's job."""
    s = masked.rstrip()
    n = len(s)
    for p in range(_UNIT_MIN, _UNIT_MAX + 1):
        if 3 * p > n:
            break
        # s[i] == s[i+p] across the last 3p chars <=> 3 copies of period p
        if s[n - 3 * p:n - p] != s[n - 2 * p:n]:
            continue
        chars = set(s[n - p:n]) - _PRECHECK_IGNORE
        if len(chars) < 5:
            continue            # rotation-invariant, C-speed: skip "aaaa…" walks
        start = n - 3 * p
        while start - p >= 0 and s[start - p:start] == s[start:start + p]:
            start -= p          # whole earlier copies
        while start > 0 and s[start - 1] == s[start - 1 + p]:
            start -= 1          # ...and the partial one the loop began with
        unit = s[start:start + p]
        if not _unit_is_meaningful(unit):
            continue
        copies = (n - start) // p
        if copies < _end_min_run(finish_reason):
            continue            # 3-4 copies at the end of a finished reply: content
        if "\n" in unit and _loop_lines_structured(s[start:]) \
                and _struct_end_allows(copies, finish_reason):
            continue            # whole list items / rows / log lines, repeated
        if prompt_text and unit * 2 in prompt_text:
            continue            # the user asked for this repetition
        return start + p
    return None


# GLUED short-unit loops: "2826HAMSTER-2826282628262826282628262826". The unit
# is below _tail_loop's 8-char floor and has too few distinct chars for it, and
# there is no whitespace, so _line_loop never sees a line. Same end-anchored
# rule as _tail_loop (a runaway loops until the cap), plus:
#   * 4+ copies at the token cap; 8+ at a natural stop, and then only for a
#     unit carrying a DIGIT -- "hahahahaha" or a CAG repeat ending a finished
#     reply is content;
#   * no whitespace in the unit (spaced repeats are _tail_loop's) and at least
#     two distinct chars one of them alnum ("aaaa" / "=-=-" are not loops here);
#   * a repeating decimal or radix literal ("0.090909…", "0b1010…") is a number;
#   * the prompt asked for it (the unit doubled, or the unit plus "repeat").
_GLUE_MIN, _GLUE_MAX = 2, 16
_GLUE_MIN_RUN_CAP = 4
_GLUE_MIN_RUN = 8
# ...and 32 on a stream still going: "1010101010101010" (8 copies) mid-sentence
# is a number the next delta continues past.
_GLUE_MIN_RUN_PARTIAL = 32
_NUMBER_PREFIX_RE = re.compile(r"(?:\d[.,]|0[xXbBoO])$")
_REPEAT_ASK_RE = re.compile(r"repeat|times|répét|fois", re.I)


def _periodic_start(s, p):
    """Smallest i with s[i:] periodic in p (s already known periodic over its
    last 4p chars). Monotone, so a binary search of C-speed slice compares --
    a 20 KB loop costs ~15 compares, not 10k stride steps."""
    n = len(s)
    lo, hi = 0, n - 4 * p
    while lo < hi:
        mid = (lo + hi) // 2
        if s[mid:n - p] == s[mid + p:n]:
            hi = mid
        else:
            lo = mid + 1
    return lo


def _glued_loop(masked, prompt_text, finish_reason):
    s = masked.rstrip()
    n = len(s)
    capped = finish_reason == "length"
    need = _GLUE_MIN_RUN_CAP if capped else (
        _GLUE_MIN_RUN_PARTIAL if finish_reason == PARTIAL else _GLUE_MIN_RUN)
    for p in range(_GLUE_MIN, _GLUE_MAX + 1):
        if 4 * p > n:
            break
        if s[n - 4 * p:n - p] != s[n - 3 * p:n]:
            continue
        tail = s[n - p:n]
        if any(c.isspace() for c in tail) or len(set(tail)) < 2:
            continue
        if not any(c.isalnum() for c in tail) or _PUA_RE.search(tail):
            continue
        start = _periodic_start(s, p)
        unit = s[start:start + p]
        if (n - start) // p < need:
            continue
        if not capped and not any(c.isdigit() for c in unit):
            continue
        head = s[:start]
        if _NUMBER_PREFIX_RE.search(head):
            continue
        if prompt_text and (unit * 2 in prompt_text
                            or (unit in prompt_text and _REPEAT_ASK_RE.search(prompt_text))):
            continue
        core = head.strip()
        if not core:
            return start + p    # the loop IS the reply: keep its first copy
        if core.startswith(unit) and not re.search(r"\s", core):
            # "2826HAMSTER-" + loop: one glued token that opens with the unit --
            # the answer, junk, then the answer again. Keep the answer.
            return (len(head) - len(head.lstrip())) + p
        return start
    return None


# SEPARATOR RUNS: "1573 1573 ------------------------------". 8+ identical
# punctuation chars running to the END, on the same line as answer text.
# A markdown rule / setext underline / fence sits on its own line and a table
# row carries "|", so neither ever qualifies. Fires at the token cap, or at any
# finish when the answer before it is itself one token repeated ("1573 1573").
_SEP_TAIL_RE = re.compile(r"([^\w\s])\1{7,}$")


def _repeated_token_end(line):
    """End offset (within `line`) of the first token when the line is one
    token repeated 2+ times ("1573 1573 "), else None."""
    toks = line.split()
    if len(toks) < 2 or any(t != toks[0] for t in toks):
        return None
    return line.index(toks[0]) + len(toks[0])


def _separator_run(masked, finish_reason):
    s = masked.rstrip()
    m = _SEP_TAIL_RE.search(s)
    if not m or _PUA_RE.match(m.group(1)):
        return None
    start = m.start()
    line_start = s.rfind("\n", 0, start) + 1
    head_line = s[line_start:start]
    if not re.search(r"\w", head_line) or "|" in head_line:
        return None
    if head_line.lstrip().startswith(m.group(1) * 3):
        return None             # a banner: "===== 5 passed in 0.12s ====="
    first = _repeated_token_end(head_line)
    if first is not None:
        return line_start + first
    if finish_reason == "length":
        return start
    return None


# LEAKED REASONING / TEMPLATE MARKERS after an answer. A reply that OPENS with
# a <think> block is how some providers ship reasoning and is left alone; only
# a marker at an odd place counts: <think> or a template token after answer
# text, "Thinking content:" after answer text, "Thought:" glued mid-line after
# a number/sentence end (not "Food for Thought:", not a ReAct line start), and
# a stray </think> with no opener that closes a SHORT head (a long head before
# it is the scratchpad itself, and its answer is after the tag -- not ours).
_THINK_OPEN_RE = re.compile(r"<think(?:ing)?>", re.I)
_THINK_CLOSE_RE = re.compile(r"</think(?:ing)?>", re.I)
_THINK_BLOCK_RE = re.compile(r"<(think|thinking)>.*?</\1>", re.I | re.S)
_THINK_LABEL_RE = re.compile(r"Thinking content\s*:", re.I)
_THOUGHT_RE = re.compile(r"\bThought:")
_TEMPLATE_TOKEN_RE = re.compile(
    r"<\|(?:im_start|im_end|endoftext|end_of_text|eot_id|eom_id|start_header_id|"
    r"end_header_id|end_of_turn|start_of_turn)\|>|<(?:end_of_turn|start_of_turn)>")
_REASON_PROMPT_RE = re.compile(r"think>|thinking content|thought:|<\||_of_turn>", re.I)
_SHORT_STRAY_HEAD = 40


def _has_answer_before(masked, pos):
    return re.search(r"\w", _THINK_BLOCK_RE.sub("", masked[:pos])) is not None


def _reasoning_leak(masked, prompt_text):
    if prompt_text and _REASON_PROMPT_RE.search(prompt_text):
        return None             # the user is asking ABOUT these markers
    hits = []
    for rx in (_THINK_OPEN_RE, _THINK_LABEL_RE, _TEMPLATE_TOKEN_RE):
        for m in rx.finditer(masked):
            if _has_answer_before(masked, m.start()):
                hits.append(m.start())
                break
    for m in _THINK_CLOSE_RE.finditer(masked):
        head = masked[:m.start()]
        if _THINK_OPEN_RE.search(head):
            continue            # a well-formed block
        core = head.strip()
        if core and len(core) <= _SHORT_STRAY_HEAD and re.search(r"\w", core):
            hits.append(m.start())
        break
    for m in _THOUGHT_RE.finditer(masked):
        before = masked[masked.rfind("\n", 0, m.start()) + 1:m.start()].rstrip()
        if before and not before[-1].isalpha() and re.search(r"\w", before):
            hits.append(m.start())
            break
    return min(hits) if hits else None


# --------------------------------------------------------------------------- #
# (d) prompt-constrained brevity: "Answer with only the number." + "8446\"Sfc
# cover\" is an additional paramet" -- a correct answer, then a same-script
# runaway no other check can call junk. When the LAST user turn explicitly
# asks for exactly one short thing, the leading short answer IS the reply.
# Guards (a false positive here trims a real answer):
#   * the ask must be imperative ("Answer with only the number", "Number
#     only.", "in one word", "reply with exactly PONG") -- "is 2 the only
#     number that..." is a question, not a format;
#   * a prompt that also asks for an explanation/steps/"then ..." is skipped,
#     and so is a long prompt (a pasted task that merely contains the phrase);
#   * never with tools (agent turns), never on a reply that opens with markup;
#   * a number must end where the number ends: "2 + 2 = 4", "10:30", "0xFF",
#     "6.02e23", "3rd", "1 573" are never cut, and a leading number the prompt
#     itself contains, followed by more digits, is an echo of the question
#     ("2825 plus 1 is 2826"), not the answer;
#   * a Capitalised word followed by another ("New York") is a name, not a word.
# --------------------------------------------------------------------------- #
_BRIEF_PROMPT_MAX = 1200
_BRIEF_KIND = (r"(?P<kind>yes or no|yes/no|oui ou non|numbers?|numerals?|digits?|integers?|"
               r"figures?|nombres?|chiffres?|words?|mots?|letters?|lettres?)")
_BRIEF_ARTS = r"(?:(?:with|by|par|avec|the|a|an|one|1|single|le|la|un|une|seul|seule)\s+)*"
_BRIEF_RES = (
    # "answer with only the number", "just the word", "uniquement par le nombre"
    (re.compile(r"\b(?:only|just|solely|exactly|nothing but|uniquement|seulement|juste)\s+"
                + _BRIEF_ARTS + _BRIEF_KIND + r"\b", re.I), True),
    # "reply with just the answer"
    (re.compile(r"\b(?:only|just)\s+(?:give\s+|return\s+|output\s+)?the\s+(?:final\s+)?"
                r"(?P<kind>answer|result|value|sum|total)\b", re.I), True),
    # "Number only."
    (re.compile(r"\b" + _BRIEF_KIND + r"\s+(?:only|uniquement|seulement)\b", re.I), True),
    # "in one word", "with a single word", "one-word answer"
    (re.compile(r"\b(?:in|with|using)\s+(?:(?:a|one|1|single)\s+)+(?P<kind>word)\b"
                r"|\b(?:one|single)[- ](?P<kind2>word)\s+(?:answer|reply|response|only)\b"
                r"|\b(?:en un|un seul)\s+(?P<kind3>mot)\b", re.I), False),
)
_BRIEF_VERB_RE = re.compile(
    r"\b(?:answer|reply|respond|give|return|output|print|say|write|provide|state|type|"
    r"r[ée]ponds|r[ée]pondez|donne|donnez|[ée]cris|[ée]crivez)", re.I)
_BRIEF_LITERAL_RE = re.compile(
    r"\b(?:reply|respond|answer|say|output|return)\s+(?:with\s+)?exactly\s*:?\s*"
    r"(?:[\"'“‘`](?P<q>[^\"'”’`\n]{1,40})[\"'”’`]|(?P<w>[A-Za-z0-9_-]{1,40})\b)", re.I)
_BRIEF_NOT_LITERAL = frozenset(("one", "a", "an", "the", "single", "two", "three", "1", "2", "3"))
_BRIEF_BLOCK_RE = re.compile(
    r"\b(?:explain|explanation|justif\w*|why|reason\w*|show (?:your |the )?work|"
    r"step[- ]by[- ]step|then|followed by|after that|if (?:yes|no|so)|pourquoi|"
    r"expliqu\w*|puis|ensuite)\b", re.I)
_NUM_KINDS = frozenset(("number", "numeral", "digit", "integer", "figure", "nombre",
                        "chiffre", "answer", "result", "value", "sum", "total"))
_WORD_KINDS = frozenset(("word", "mot"))
_LETTER_KINDS = frozenset(("letter", "lettre"))
_YN_KINDS = frozenset(("yes or no", "yes/no", "oui ou non"))
_LEAD_NUM_RE = re.compile(
    r"\s*[-+−]?\$?(?:\d{1,3}(?:[ \xa0 ]\d{3})+(?!\d)|\d+(?:,\d{3})*(?:[.,]\d+)?)%?")
_NUM_CONT_RE = re.compile(
    r"\s*[-+*/×÷=^<>:]|[0-9A-Fa-f]+\b|[eE][+-]?\d|[xXbBoO][0-9A-Fa-f]|(?:st|nd|rd|th)\b")
_LEAD_WORD_RE = re.compile(r"\s*[A-Za-zÀ-ÖØ-öø-ɏ][A-Za-zÀ-ÖØ-öø-ɏ0-9'’]*(?:-[A-Za-zÀ-ÖØ-öø-ɏ0-9]+)*")
_LEAD_YN_RE = re.compile(r"\s*(?:yes|no|oui|non)\b", re.I)
_TRAILING_OK = " \t\r\n.!?。"


def _brief_kinds(prompt):
    """{kind classes} the prompt imperatively constrains the reply to, plus a
    literal token for "reply with exactly X" (or None)."""
    kinds = set()
    for rx, needs_verb in _BRIEF_RES:
        for m in rx.finditer(prompt):
            if needs_verb:
                cut = max(prompt.rfind(c, 0, m.start()) for c in ".?!\n;")
                lead = prompt[cut + 1:m.start()]
                if lead.strip() and not _BRIEF_VERB_RE.search(lead):
                    continue    # "is 2 the only number that...": not a format
            kind = next(g for g in m.groups() if g).lower()
            kind = kind if kind in _YN_KINDS else kind.rstrip("s")
            if kind in _NUM_KINDS:
                kinds.add("num")
            elif kind in _WORD_KINDS:
                kinds.add("word")
            elif kind in _LETTER_KINDS:
                kinds.add("letter")
            elif kind in _YN_KINDS:
                kinds.add("yn")
    literal = None
    m = _BRIEF_LITERAL_RE.search(prompt)
    if m:
        literal = m.group("q") or m.group("w")
        if literal and literal.lower() in _BRIEF_NOT_LITERAL:
            literal = None
    return kinds, literal


_GLUED_NUM_MIN_UNIT = 3          # "121212" / "111" can be real answers
_GLUED_NUM_MIN_COPIES = 3


def _glued_number_period(num):
    """Unit length when an all-digit `num` is one 3+ digit unit glued to
    itself 3+ times (a trailing partial copy allowed: the cap cut it), else
    None. MEASURED LIVE (stream, llm7/GLM-5.3-Flash, "What is 3191 plus 1?
    Answer with only the number.", max_tokens 40): "319231923192". A number
    with a shorter period ("111111", "121212") is left alone -- those are
    plausible real answers, and a false cut here trims one."""
    if not num.isdigit():
        return None
    n = len(num)
    for short in (1, 2):
        if n > short and num == (num[:short] * n)[:n]:
            return None
    for p in range(_GLUED_NUM_MIN_UNIT, n // _GLUED_NUM_MIN_COPIES + 1):
        if num == (num[:p] * (n // p + 1))[:n]:
            return p
    return None


@functools.lru_cache(maxsize=64)
def _brevity(prompt):
    """(frozenset of kinds, literal) the LAST user turn -- its own words, CLI
    wrappers removed -- imperatively constrains the reply to; (frozenset(),
    None) when it does not, or when a guard says it is not a bare-value
    format (a long pasted task, an explanation also asked for)."""
    p = _instruction(prompt) if isinstance(prompt, str) else None
    if not p or len(p) > _BRIEF_PROMPT_MAX or _BRIEF_BLOCK_RE.search(p):
        return frozenset(), None
    kinds, literal = _brief_kinds(p)
    return frozenset(kinds), literal


def brevity_ask(last_prompt):
    """True when the last user turn asks for one bare value ("Reply with only
    the number", "in one word", "reply with exactly PONG"). The stream gate
    then holds the whole short answer and judges it before release. Never
    raises (False)."""
    try:
        kinds, literal = _brevity(last_prompt if isinstance(last_prompt, str) else
                                  (str(last_prompt) if last_prompt else None))
        return bool(kinds or literal)
    except Exception:                                            # noqa: BLE001
        return False


# "2768.2768" / "11991199.1199" for "What is 2767 plus 1? Answer with only the
# number." (REPORTED 2026-09-28): the answer, a dot, and the answer again --
# the same glued-copy degeneration as "319231923192", but with a dot in it the
# whole thing IS a well-formed decimal. Cutting it would trim a reply that
# could be a real value (a price, a version-like figure), so it is never cut:
# it is only FLAGGED ("echoed_decimal", ok stays True) so the caller can file
# a junk quality strike for the (provider, model) that said it. Guards: a
# constrained number ask, no tools, the right side 3+ digits, the left side
# 1+ whole copies of it, and the value not in the prompt.
_ECHOED_DECIMAL_RE = re.compile(r"\s*[-+]?(?P<left>\d+)\.(?P<right>\d{3,})\s*[.!]?\s*")


def echoed_decimal(text, last_prompt, tools_offered=False):
    """True when `text` is a bare number made of one digit run repeated around
    a dot ("2768.2768", "11991199.1199") under a "only the number" ask. A
    QUALITY SIGNAL, never a cut. Never raises (False)."""
    try:
        if tools_offered or not isinstance(text, str) or not last_prompt:
            return False
        kinds, _literal = _brevity(last_prompt if isinstance(last_prompt, str)
                                   else str(last_prompt))
        if "num" not in kinds:
            return False
        m = _ECHOED_DECIMAL_RE.fullmatch(text)
        if not m:
            return False
        left, right = m.group("left"), m.group("right")
        if len(left) % len(right) or left != right * (len(left) // len(right)):
            return False
        value = "%s.%s" % (left, right)
        return value not in (_instruction(last_prompt) or "")
    except Exception:                                            # noqa: BLE001
        return False


def _constrained_extra(text, prompt, tools_offered):
    if tools_offered or not prompt:
        return None
    kinds, literal = _brevity(prompt)
    if not kinds and not literal:
        return None
    prompt = _instruction(prompt)   # the echo checks below: the user's words only
    head = text[:400]
    cut = None
    if literal:
        lead = len(head) - len(head.lstrip())
        if head[lead:lead + len(literal)].lower() == literal.lower():
            end = lead + len(literal)
            if end >= len(head) or not head[end].isalnum():
                cut = end
    if cut is None and "num" in kinds:
        m = _LEAD_NUM_RE.match(head)
        suffix = _GLUE_RUN_RE.match(head, m.end()) if m else None
        if suffix and _suffix_ok(suffix.group(0)):
            m = None            # "5ème", "1º", "10µs": the number's own suffix
        if m and not _NUM_CONT_RE.match(head, m.end()):
            num = m.group(0).strip()
            p = _glued_number_period(num)
            if p and num not in prompt:
                # "319231923192": the answer glued to copies of itself. Every
                # copy is inside ONE numeric token, so the checks above see a
                # single long number that "ends where the number ends".
                cut = m.end() - len(num) + p
            else:
                echo = re.search(r"(?<![\d.,])" + re.escape(num) + r"(?![\d.,]*\d)", prompt)
                if not (echo and re.search(r"\d", head[m.end():])):
                    cut = m.end()
    if cut is None and "yn" in kinds:
        m = _LEAD_YN_RE.match(head)
        if m:
            cut = m.end()
    if cut is None and ("word" in kinds or "letter" in kinds):
        m = _LEAD_WORD_RE.match(head)
        if m:
            word = m.group(0).strip()
            name = word[:1].isupper() and re.match(r"[ \t]+[A-Z]", head[m.end():])
            if ("word" in kinds or len(word) == 1) and not name:
                cut = m.end()
    if cut is None:
        return None
    if not text[cut:].strip(_TRAILING_OK):
        return None             # nothing extra: the reply complied
    return cut


# --------------------------------------------------------------------------- #
# (e) letters of another Unicode block glued straight onto a bare number
# --------------------------------------------------------------------------- #
# "4349âmara=..." for "Reply with only the number.": the number the prompt
# asked for BARE, then -- no space, no punctuation -- a word whose letters
# come from outside Basic Latin. _constrained_extra would call any extra text
# junk, but stands down on tool turns ("4. Done." may be an agent's report);
# this needs the glued shape, so it runs on tool turns too. Guards:
#   * only for a "num" brevity ask (a word ask is left alone: "café",
#     "Zürich" glue accented letters onto ASCII ones legitimately);
#   * the glued run is 3+ letters and not an ordinal / unit / constant
#     ("5ème", "1ère", "1º", "5ᵉ", "10µs", "10kΩ", "2π");
#   * no letter of that block anywhere in the prompt: a French or Spanish
#     conversation is not a switch to "another" block;
#   * the number-shape guards of _constrained_extra ("0xFF", "6.02e23", an
#     echo of the prompt's own number followed by more digits).
_GLUE_RUN_RE = re.compile(r"[^\W\d_]+")
_GLUED_FOREIGN_MIN = 3
_NUM_SUFFIX_OK_RE = re.compile(
    r"st|nd|rd|th|e|er|re|ère|ere|ème|eme|ième|ieme|nde|o|a|os|as|[ºª]|"
    r"[µμ][a-z]{0,3}|[kKmMG]?[ΩΩ]|[ÅÅ]", re.I)


def _suffix_ok(run):
    """True for letters that legitimately follow a number: an ordinal, a
    unit, a superscript ordinal, a one/two-letter math constant."""
    if _NUM_SUFFIX_OK_RE.fullmatch(run):
        return True
    if all(unicodedata.category(c) == "Lm" for c in run):
        return True                     # "5ᵉ", "1ᵉʳ"
    return len(run) <= 2 and all(0x370 <= ord(c) < 0x400 or 0x2100 <= ord(c) < 0x2150
                                 for c in run)      # "2π", "3ℏ"


def _letter_block(ch):
    cp = ord(ch)
    if cp < 0x80:
        return "ascii"
    if cp < 0x250 or 0x1E00 <= cp < 0x1F00:
        return "latin"                  # Latin-1 / Extended-A/B / Additional
    for key, rx in _SCRIPT_ANY.items():
        if rx.match(ch):
            return key
    return cp >> 7


def _glued_foreign(text, last_prompt, prompt_text):
    if not last_prompt:
        return None
    kinds, _literal = _brevity(last_prompt)
    if "num" not in kinds:
        return None
    head = text[:400]
    m = _LEAD_NUM_RE.match(head)
    if not m or _NUM_CONT_RE.match(head, m.end()):
        return None
    run = _GLUE_RUN_RE.match(head, m.end())
    if not run:
        return None
    word = run.group(0)
    blocks = {_letter_block(c) for c in word if ord(c) >= 0x80}
    if not blocks or len(word) < _GLUED_FOREIGN_MIN or _suffix_ok(word):
        return None
    own = _instruction(last_prompt) or ""
    num = m.group(0).strip()
    echo = re.search(r"(?<![\d.,])" + re.escape(num) + r"(?![\d.,]*\d)", own)
    if echo and re.search(r"\d", head[m.end():]):
        return None             # "2825âbc 2826": the question's number echoed
    for ref in (own, _instruction(prompt_text) if prompt_text else ""):
        if any(ord(c) >= 0x80 and c.isalpha() and _letter_block(c) in blocks
               for c in ref or ""):
            return None         # the conversation writes that block itself
    return m.end()


# --------------------------------------------------------------------------- #
# (f) leaked metadata / chat-template markers after a short answer
# --------------------------------------------------------------------------- #
# "4349âmara=METADATA:8;Note: TOKEN count=298121; REF:5": training-data
# metadata and prompt-template scaffolding the model kept generating after
# its answer. None of it is prose a reply means to contain, but each marker
# alone can appear in a real answer (an S3 doc naming METADATA, a Llama 2
# explainer quoting [INST]), so a marker counts only when
#   * a BARE short answer precedes it ("4349", "Answer: 42", "Yes.") -- the
#     reply was done, and the template went on; or
#   * two different metadata kinds (METADATA / TOKEN count / REF:n) cluster,
#     which no answer writes;
# never when the prompt names any of them, never in code, never at the start.
_META_MARKER_RE = re.compile(
    r"(?P<meta>[=;|]\s*METADATA\b|\bMETADATA\s*[:=]\s*\d)"
    r"|(?P<tok>(?i:\btoken[ _]?count)\s*[=:]\s*\d)"
    r"|(?P<ref>\bREF:\s*\d)"
    r"|(?P<tpl><[|｜][\w.:\-▁]{1,40}[|｜]>|\[/?INST\]|<</?SYS>>|</s>"
    r"|<(?:eos|bos|pad|unk)>"
    r"|^[ \t]*#{2,3}[ \t]*(?:Instruction|Input|Response|Human|Assistant|System)[ \t]*:)",
    re.M)
_META_PROMPT_RE = re.compile(
    r"metadata|token[ _]?count|\bref:|<[|｜]|\[/?inst\]|<</?sys>>|</s>|"
    r"<(?:eos|bos|pad|unk)>|#{2,3}\s*(?:instruction|input|response|human|assistant|system)\b",
    re.I)
_META_CLUSTER = frozenset(("meta", "tok", "ref"))
_BARE_HEAD_RE = re.compile(
    r"\s*(?:[A-Za-z]{1,12}:\s*)?(?:[-+−]?\$?\d[\d,.]*%?|[^\W_]{1,20})[.!]?\s*")
# "4349 Note: TOKEN count=": the label introducing the junk goes with it
_LABEL_TAIL_RE = re.compile(r"(?:(?<=\s)|(?<=[;,])|^)[A-Za-z]{1,12}:\s*$")
_META_SEP_TAIL = " \t\r\n=;:|,"


def _glued_run_start(text, end):
    """Start of a junk letter run glued onto a number ending at `end`
    ("4349âmara" -> 4), else `end`. An ordinal/unit/constant stays, and so
    does a 1-2 letter ASCII tail ("42km")."""
    i = end
    while i > 0 and text[i - 1].isalpha():
        i -= 1
    if i == end or i == 0 or not text[i - 1].isdigit():
        return end
    run = text[i:end]
    if _suffix_ok(run) or (len(run) < _GLUED_FOREIGN_MIN and run.isascii()):
        return end
    return i


def _meta_cut(text, pos):
    """Where the clean answer before a marker at `pos` ends: a dangling label
    and separators go, and so does a junk letter run glued onto a number
    ("4349âmara=METADATA" -> "4349")."""
    head = text[:pos]
    m = _LABEL_TAIL_RE.search(head)
    if m:
        head = head[:m.start()]
    return _glued_run_start(text, len(head.rstrip(_META_SEP_TAIL)))


def _meta_leak(masked, text, prompt_text, at_start=True):
    """Offset of leaked metadata/template junk in `text` (indices shared with
    `masked`), or None. `at_start`: `text` is the reply's head, so the
    bare-answer rule may run (a stream window's head is not the reply's)."""
    hits = [m for m in _META_MARKER_RE.finditer(masked)
            if _has_answer_before(masked, m.start())]
    if not hits:
        return None
    ref = _instruction(prompt_text) if prompt_text else ""
    if ref and _META_PROMPT_RE.search(ref):
        return None             # the user is asking ABOUT these markers
    if at_start:
        cut = _meta_cut(text, hits[0].start())
        if cut and _BARE_HEAD_RE.fullmatch(_THINK_BLOCK_RE.sub("", masked[:cut])):
            return cut
    if len({m.lastgroup for m in hits} & _META_CLUSTER) >= 2:
        first = next(m for m in hits if m.lastgroup in _META_CLUSTER)
        return _meta_cut(text, first.start())
    return None


# --------------------------------------------------------------------------- #
# (c) leaked tool-call markup in a plain-chat answer
# --------------------------------------------------------------------------- #
_LEAK_RE = re.compile(r"</?tool_call\b[^>]{0,40}>|</?arg_(?:key|value)>", re.I)
_LEAK_PROMPT_RE = re.compile(r"tool_call|arg_value|arg_key", re.I)


def _markup_leak(masked, prompt_text, tools_offered):
    if tools_offered:
        return None             # typed-tool-call / tool_rescue own this shape
    if prompt_text and _LEAK_PROMPT_RE.search(prompt_text):
        return None             # the user is asking ABOUT this markup
    m = _LEAK_RE.search(masked)
    return m.start() if m else None


# A salvage must never turn one number into ANOTHER. The periodic scan in
# _glued_loop walks back over every char that fits the loop, so "2826" followed
# by a "26" loop ("282626262626...") starts the loop at index 2 and would serve
# "28" -- a different number, stated with full confidence. So a cut that lands
# INSIDE a digit run is only kept when everything after it in that run is
# copies of the kept number ("2826" + "28262826..."): that is the first copy of
# the loop, not a prefix of a longer number. Otherwise: no salvage (next hop).
_TRAIL_DIGITS_RE = re.compile(r"\d+$")
_LEAD_DIGITS_RE = re.compile(r"\d+")


def _splits_a_number(text, clean):
    after = text[len(clean):len(clean) + 1]
    if not after.isdigit():
        return False
    if clean[-1:] in ".," and clean[-2:-1].isdigit():
        return True                    # "3." + "14159": a decimal split
    lead = _TRAIL_DIGITS_RE.search(clean)
    if not lead:
        return False
    unit = lead.group(0)
    run = _LEAD_DIGITS_RE.match(text, len(clean)).group(0)
    return run != (unit * (len(run) // len(unit) + 1))[:len(run)]


# A reply that is NOTHING but chat-template tokens and punctuation. MEASURED
# live 2026-09-27 on a codex `exec resume` turn: nvidia/kimi-k3 streamed
# "<|close|>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" and it shipped as the answer --
# the head has "close" in it, so the separator-run check saw answer text, and
# "<|close|>" is not one of the known template tokens. No word outside a
# <|...|> token = no answer: cut at 0, no salvage, the chain moves on.
_ANY_SPECIAL_TOKEN_RE = re.compile(r"<[|｜][\w.:\-▁]{1,40}[|｜]>")
# one stray word glued to the token, then only a punctuation run to the end
_TOKEN_WORD_RUN_RE = re.compile(r"^\s*\w{1,16}\s*([^\w\s])\1{7,}\s*$")


def _special_token_junk(text, prompt_text):
    if prompt_text and ("<|" in prompt_text or "<｜" in prompt_text):
        return None             # the user is asking ABOUT these tokens
    if not _ANY_SPECIAL_TOKEN_RE.search(text):
        return None
    rest = _ANY_SPECIAL_TOKEN_RE.sub(" ", text)
    if _TOKEN_WORD_RUN_RE.match(rest):
        return 0                # "<|close|>think!!!!!!!!" (same turn, next try)
    if re.search(r"\w", rest):
        return None
    # A stream head that so far holds only "<|x|>" may still turn into an
    # answer; junk is the token PLUS a run of punctuation after it.
    return 0 if len(re.sub(r"\s", "", rest)) >= 8 else None


def _clip(text):
    if len(text) <= _MAX_SCAN:
        return text
    return text[-_MAX_SCAN:]


# --------------------------------------------------------------------------- #
# A second answer glued onto the first
# --------------------------------------------------------------------------- #
# MEASURED LIVE 2026-09-27 (Claude Code `-p --model max` through the hub): ONE
# upstream stream carried two complete answers back to back, the second glued
# on with no separator at all --
#   "...Nothing else needed. Next: what would you like to do?The last line of
#    big3.txt is: ..."
# -- the model's end-of-turn token was dropped by the provider and sampling
# ran on into a fresh answer. Claude Code prints the last text block, so the
# user saw both. (Verified against the real CLI with a fake server: a SECOND
# block or a second message is never glued in `-p` output; only one block
# holding both answers is.) The signature: the reply's own opening line
# restated right after a non-space character -- a stripped token leaves no
# whitespace, and a real answer does not restate its first sentence glued
# onto its last one.
RESTART_KEY_MAX = 40
_RESTART_KEY_MIN = 18
_RESTART_KEY_WORDS = 3
_RESTART_WORD_RE = re.compile(r"[^\W_]{2,}")
# What may END the first answer right before a glued restatement.
_RESTART_PREV = frozenset('.!?)]}"\'`*’”')
# ...of which these also OPEN a quote / span when a space precedes them.
_RESTART_OPENERS = frozenset('"\'`*’”')


def restart_key(text):
    """The opening a glued second answer would restate: the reply's first
    non-empty line, stripped, cut to RESTART_KEY_MAX chars -- or None when it
    is too short or too plain to be distinctive (a bare "4", "Yes.", a code
    fence) or not complete yet (no newline and under RESTART_KEY_MAX chars).
    Never raises."""
    try:
        if not isinstance(text, str):
            return None
        s = text[:2048].lstrip()          # the head only: O(1) on a long stream
        nl = s.find("\n")
        if nl < 0 and len(s) < RESTART_KEY_MAX:
            return None
        line = s if nl < 0 else s[:nl]
        key = line.strip()[:RESTART_KEY_MAX]
        if len(key) < _RESTART_KEY_MIN or key.startswith("```"):
            return None
        if len(_RESTART_WORD_RE.findall(key)) < _RESTART_KEY_WORDS:
            return None
        return key
    except Exception:                                            # noqa: BLE001
        return None


def restart_boundary(before, cur):
    """The character test of restart_glued_at: `before` is the text right
    before the restatement (its last two characters are enough), `cur` the
    restatement's first character. Never raises."""
    try:
        if not before or not cur:
            return False
        prev = before[-1]
        if prev.isspace():
            return False
        if prev.isalnum():
            return cur.isupper()              # else one word running on
        if prev not in _RESTART_PREV:
            return False
        if prev in _RESTART_OPENERS and (len(before) < 2 or before[-2].isspace()):
            return False                      # an opening quote/emphasis, not an end
        return True
    except Exception:                                            # noqa: BLE001
        return False


def restart_glued_at(text, q):
    """True when a restatement starting at `q` is glued onto what precedes it:
    the answer before it ENDS right there (sentence punctuation, a closing
    bracket/quote/fence, or a word run straight into a capital), not inside a
    code fence, and not an opening quote / a word running on. Never raises."""
    try:
        if q <= 0 or q >= len(text):
            return False
        if not restart_boundary(text[max(0, q - 2):q], text[q]):
            return False
        return text.count("```", 0, q) % 2 == 0
    except Exception:                                            # noqa: BLE001
        return False


def glued_restart(text, key=None, start=0, first_end=None):
    """Offset in `text` where a glued second answer starts (see above), or
    None. `key` defaults to restart_key(text); `first_end` (where the opening
    itself ends) is found when not given. Only occurrences at or after
    `start` are looked at, so a stream re-checks just its new text. Never
    raises."""
    try:
        if not isinstance(text, str):
            return None
        key = key or restart_key(text)
        if not key:
            return None
        if first_end is None:
            first = text.find(key)
            if first < 0:
                return None
            first_end = first + len(key)
        pos = max(first_end, start)
        while True:
            q = text.find(key, pos)
            if q < 0:
                return None
            if restart_glued_at(text, q):
                return q
            pos = q + 1
    except Exception:                                            # noqa: BLE001
        return None


# --------------------------------------------------------------------------- #
# Early release for the stream hold-back gate
# --------------------------------------------------------------------------- #
# The gate holds a stream's first visible text until it can judge it. Every
# junk sample it exists for is SHORT or GLUED: "3324TouchableOpacity_FP$.
# Actually, the answer is" (a brevity prompt), "319231923192" (a glued loop),
# a leaked <think>/<|im_end|>. Once the held text is ordinary prose or code,
# waiting for 400 chars / 2.5 s only costs first-token latency, so the gate
# releases as soon as reads_as_answer() says so (inspect() still judges it).
EARLY_MIN_CHARS = 80
_EARLY_MIN_WORDS = 10
_EARLY_MIN_DISTINCT = 0.6       # distinct words / words
_EARLY_MAX_WORD = 40            # a longer "word" is a glued run or a blob
_EARLY_MIN_WORDCHAR = 0.55      # letters+digits share of non-space chars
_EARLY_MARKER_RE = re.compile(r"<\s*/?\s*(?:think|thinking|tool_call|arg_)|<\||\|>|"
                              r"\bThought:|Thinking content", re.I)


def reads_as_answer(text, *, last_prompt=None):
    """True when `text` (the start of a streamed reply, no finish yet) already
    reads as a normal answer: >= EARLY_MIN_CHARS of varied words, no glued
    run, no reasoning/template marker, and the prompt does not constrain the
    reply to a number/word/yes-no (there the whole short answer IS the
    thing judged). Code counts: it has words and punctuation too. Never
    raises (False)."""
    try:
        if not isinstance(text, str) or len(text.strip()) < EARLY_MIN_CHARS:
            return False
        if last_prompt:
            lp = _instruction(str(last_prompt)) or ""
            if len(lp) <= _BRIEF_PROMPT_MAX:
                kinds, literal = _brief_kinds(lp)
                if kinds or literal:
                    return False
        if _EARLY_MARKER_RE.search(text):
            return False
        words = text.split()
        if len(words) < _EARLY_MIN_WORDS:
            return False
        if max(len(w) for w in words) > _EARLY_MAX_WORD:
            return False
        if len(set(words)) < _EARLY_MIN_DISTINCT * len(words):
            return False
        dense = [c for c in text if not c.isspace()]
        if sum(1 for c in dense if c.isalnum()) < _EARLY_MIN_WORDCHAR * len(dense):
            return False
        return True
    except Exception:                                            # noqa: BLE001
        return False


def inspect(text, *, prompt_text=None, tools_offered=False, finish_reason=None,
            last_prompt=None, partial=False):
    """Judge one answer's text.

    Returns {"ok": bool, "reasons": [...], "salvage": str|None}. `reasons` may
    hold "truncated" even when ok is True (informational). `salvage` is the
    clean answer before the junk started, or None when the junk is not just a
    tail (nothing meaningful precedes it). `last_prompt` is the LAST user
    turn: the brevity constraint ("answer with only the number") is read from
    it alone, since an earlier turn's format request does not bind a later
    "now explain why"; it defaults to `prompt_text`. Never raises: any
    internal error reports ok=True -- the gate must never be the thing that
    loses an answer. `partial`: `text` is a stream still in progress (no
    finish yet), so loops reaching its current end need the mid-text copy
    count and an inline code span still open at the end is masked."""
    result = {"ok": True, "reasons": [], "salvage": None}
    try:
        if not isinstance(text, str) or not text.strip():
            return result
        if prompt_text is not None and not isinstance(prompt_text, str):
            prompt_text = str(prompt_text)
        if last_prompt is None:
            last_prompt = prompt_text
        elif not isinstance(last_prompt, str):
            last_prompt = str(last_prompt)
        if finish_reason == "length":
            result["reasons"].append("truncated")
        # Long answers: judge the tail only. A loop or leak that ran to the cap
        # is AT the tail, and indices below are shifted back onto `text`.
        offset = max(0, len(text) - _MAX_SCAN)
        body = _clip(text)
        masked = _mask_code(body, partial)
        loop_masked = _mask_fences_distinct(body)
        loop_fin = PARTIAL if partial and not finish_reason else finish_reason
        cuts = []
        checks = (
            ("runaway_script", lambda: _script_switch(body, masked, prompt_text,
                                                      finish_reason, at_start=offset == 0)),
            ("repetition", lambda: _line_loop(loop_masked, prompt_text, loop_fin)),
            ("repetition", lambda: _tail_loop(loop_masked, prompt_text, loop_fin)),
            ("repetition", lambda: _glued_loop(loop_masked, prompt_text, loop_fin)),
            ("separator_run", lambda: _separator_run(masked, finish_reason)),
            ("tool_markup", lambda: _markup_leak(masked, prompt_text, tools_offered)),
            ("reasoning_leak", lambda: _reasoning_leak(masked, prompt_text)),
            ("template_junk", lambda: (None if offset else
                                       _special_token_junk(body, prompt_text))),
            ("metadata_leak", lambda: _meta_leak(masked, body, prompt_text,
                                                 at_start=offset == 0)),
        )
        for reason, fn in checks:
            cut = fn()
            if cut is None:
                continue
            if reason not in result["reasons"]:
                result["reasons"].append(reason)
            cuts.append(offset + cut)
        # judged on the reply's HEAD (a leading answer), so never offset
        cut = _constrained_extra(text, last_prompt, tools_offered)
        if cut is not None:
            result["reasons"].append("extra_text")
            cuts.append(cut)
        cut = _glued_foreign(text, last_prompt, prompt_text)
        if cut is not None:
            result["reasons"].append("glued_junk")
            cuts.append(cut)
        cut = glued_restart(text)
        if cut is not None:
            result["reasons"].append("restarted")
            cuts.append(cut)
        # Informational like "truncated": flagged, never cut (see
        # echoed_decimal). Only on a finished reply -- a stream in progress
        # may still be writing the real answer.
        if not partial and echoed_decimal(text, last_prompt, tools_offered):
            result["reasons"].append("echoed_decimal")
        if not cuts:
            return result
        result["ok"] = False
        clean = text[:min(cuts)].rstrip()
        if re.search(r"\w", clean) and not _splits_a_number(text, clean):
            result["salvage"] = clean
        return result
    except Exception:                                            # noqa: BLE001
        return {"ok": True, "reasons": [], "salvage": None}


# --------------------------------------------------------------------------- #
# Rolling tail check for a stream still in progress
# --------------------------------------------------------------------------- #
# 8 copies (the mid-text count) of a 160-char unit must fit.
TAIL_WINDOW = 1300


def inspect_tail(text, *, window=TAIL_WINDOW, prompt_text=None, tools_offered=False,
                 state=None, last_prompt=None):
    """Offset in `text` where junk starts, judged on its last `window` chars
    only, or None. For a STREAM already released to the client: run on every
    visible delta, so it must stay O(window), and it never judges the head
    (inspect() did that once, on the hold-back window).

    Only the tail-shaped failures: a loop running to the current end, a
    separator run, a script switch, leaked tool/reasoning/metadata markup.
    The head-shaped ones (the brevity trim, a junk run glued onto the bare
    number) run only while the WHOLE text still fits the window and
    `last_prompt` asks for a bare value: a short answer released by the hold
    window's clock ("4349" after 2.5 s of a slow model) may still grow the
    junk that inspect() never saw. No finish_reason: the stream has not
    finished, so its current end is not the answer's end and a loop reaching
    it needs the MID-text copy count (a line printed five times mid-answer is
    content until it keeps
    going). Fence state comes from the FULL text, so a window opening inside
    a code block still has that code masked. `state` (a dict the caller keeps
    per stream) caches the foreign-script scan of the text before the window,
    so repeated calls on a growing text stay O(new text). Never raises
    (None)."""
    try:
        if not isinstance(text, str) or not text.strip():
            return None
        if prompt_text is not None and not isinstance(prompt_text, str):
            prompt_text = str(prompt_text)
        start = max(0, len(text) - int(window))
        if start:
            # Open the window on a line start: a window beginning mid-"```"
            # would read the fence as prose and its code as a loop.
            line = text.rfind("\n", 0, start) + 1
            if start - line <= window:
                start = line
        pad = "```\n" if text.count("```", 0, start) % 2 else ""
        body = pad + text[start:]
        masked = _mask_code(body, True)
        loop_masked = _mask_fences_distinct(body)
        # A reply ALREADY in a foreign script is not switching now; whole-reply
        # script judgement was inspect()'s job on the head.
        if state is None:
            state = {}
        pos = state.get("fpos", 0)
        if pos > start:
            pos, state["foreign"] = 0, False
        if not state.get("foreign") and pos < start:
            state["foreign"] = _ANY_FOREIGN_RE.search(text, pos, start) is not None
        state["fpos"] = start
        script = None
        if not (start and state.get("foreign")):
            script = _script_switch(body, masked, prompt_text, None, at_start=start == 0)
        # A stray </think> only counts closing a SHORT head (inspect's rule); a
        # window's own head is not the reply's, so mid-stream it never counts.
        lead = _THINK_CLOSE_RE.sub(lambda m: " " * len(m.group(0)), masked) \
            if start else masked
        found = [c for c in (
            script,
            _line_loop(loop_masked, prompt_text, PARTIAL),
            _tail_loop(loop_masked, prompt_text, PARTIAL),
            _glued_loop(loop_masked, prompt_text, PARTIAL),
            _separator_run(masked, None),
            _markup_leak(masked, prompt_text, tools_offered),
            _reasoning_leak(lead, prompt_text),
            _meta_leak(masked, body, prompt_text, at_start=start == 0),
        ) if c is not None]
        if start == 0 and last_prompt:
            # the whole reply is in view (pad is "" at start 0): judge its head
            lp = last_prompt if isinstance(last_prompt, str) else str(last_prompt)
            found.extend(c for c in (_constrained_extra(text, lp, tools_offered),
                                     _glued_foreign(text, lp, prompt_text))
                         if c is not None)
        # A glued second answer (restart_key reads only the reply's head).
        r = glued_restart(text, start=start)
        if r is not None:
            found.append(r - start + len(pad))
        if not found:
            return None
        return max(0, start + min(found) - len(pad))
    except Exception:                                            # noqa: BLE001
        return None
